# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.16.2
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=illageandspillage
# The human-readable display name for the mod.
mod_name=Illage and Spillage: Respillaged
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=All Rights Reserved
# The mod version. See https://semver.org/
mod_version=1.2.8
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
maven_group=com.yellowbrossproductions.illageandspillage
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=Original mod by Yellowbross Productions, port and subsequent updates by TheDarkPeasant. Fabric port by CrawKatt
mod_description=A continuation of Yellowbross Productions's Illage and Spillage ported to Fabric.