package com.yellowbrossproductions.illageandspillage.init;


import com.yellowbrossproductions.illageandspillage.IllageAndSpillage;
import com.yellowbrossproductions.illageandspillage.entities.*;
import com.yellowbrossproductions.illageandspillage.entities.projectile.*;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EntityType.Builder;
import net.minecraft.world.entity.MobCategory;

public class ModEntityTypes {
    public static final EntityType<IgniterEntity> Igniter;
    public static final EntityType<EngineerEntity> Engineer;
    public static final EntityType<ChagrinSentryEntity> ChagrinSentry;
    public static final EntityType<HinderEntity> Hinder;
    public static final EntityType<FactoryEntity> Factory;
    public static final EntityType<BeeperEntity> Beeper;
    public static final EntityType<SniperEntity> Sniper;
    public static final EntityType<PokerEntity> Poker;
    public static final EntityType<MagispellerEntity> Magispeller;
    public static final EntityType<FakeMagispellerEntity> Faker;
    public static final EntityType<DispenserEntity> Dispenser;
    public static final EntityType<IllashooterEntity> Illashooter;
    public static final EntityType<CrashagerEntity> Crashager;
    public static final EntityType<BossRandomizerEntity> BossRandomizer;
    public static final EntityType<TwittollagerEntity> Twittollager;
    public static final EntityType<SpiritcallerEntity> Spiritcaller;
    public static final EntityType<MobSpiritEntity> MobSpirit;
    public static final EntityType<IllagerSoulEntity> IllagerSoul;
    public static final EntityType<ImpEntity> Imp;
    public static final EntityType<SpiritHandEntity> SpiritHand;
    public static final EntityType<SoulBeamEntity> SoulBeam;
    public static final EntityType<IgniterFireballEntity> IgniterFireball;
    public static final EntityType<CrocofangEntity> Crocofang;
    public static final EntityType<CameraShakeEntity> CameraShake;
    //    public static final EntityType<DevastatorEntity> Devastator;
    public static final EntityType<AbsorberEntity> Absorber;
    public static final EntityType<PreserverEntity> Preserver;
    public static final EntityType<FreakagerEntity> Freakager;
    public static final EntityType<RagnoEntity> Ragno;
    public static final EntityType<EyesoreEntity> Eyesore;
    public static final EntityType<FunnyboneEntity> Funnybone;
    public static final EntityType<BoneEntity> Bone;
    public static final EntityType<SkullBombEntity> SkullBomb;
    public static final EntityType<OldFreakagerEntity> OldFreakager;
    public static final EntityType<OldRagnoEntity> OldRagno;
    public static final EntityType<OldMagispellerEntity> OldMagispeller;
    public static final EntityType<MagiFireballEntity> MagiFireball;
    public static final EntityType<MagiArrowEntity> MagiArrow;
    public static final EntityType<MagiHealEntity> MagiHeal;
    public static final EntityType<KaboomerEntity> Kaboomer;
    public static final EntityType<PumpkinBombEntity> PumpkinBomb;
    public static final EntityType<AxeEntity> Axe;
    public static final EntityType<OldAxeEntity> OldAxe;
    public static final EntityType<DarkPotionEntity> DarkPotion;
    public static final EntityType<ScytheEntity> Scythe;
    public static final EntityType<OldScytheEntity> OldScythe;
    public static final EntityType<TrickOrTreatEntity> TrickOrTreat;
    public static final EntityType<WebEntity> Web;
    public static final EntityType<WebNetEntity> WebNet;
    public static final EntityType<VillagerSoulEntity> VillagerSoul;

    public static void onAttribute() {
        FabricDefaultAttributeRegistry.register(Igniter, IgniterEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Engineer, EngineerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(ChagrinSentry, ChagrinSentryEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Hinder, HinderEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Factory, FactoryEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Beeper, BeeperEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Sniper, SniperEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Poker, PokerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Magispeller, MagispellerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Faker, FakeMagispellerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Dispenser, DispenserEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Illashooter, IllashooterEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Crashager, CrashagerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(BossRandomizer, BossRandomizerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Twittollager, TwittollagerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Spiritcaller, SpiritcallerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(MobSpirit, MobSpiritEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(IllagerSoul, IllagerSoulEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Imp, ImpEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(SpiritHand, SpiritHandEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Crocofang, CrocofangEntity.createAttributes().build());
//        FabricDefaultAttributeRegistry.register(Devastator, DevastatorEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Absorber, AbsorberEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Preserver, PreserverEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Freakager, FreakagerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Ragno, RagnoEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Eyesore, EyesoreEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Funnybone, FunnyboneEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(SkullBomb, SkullBombEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(OldFreakager, OldFreakagerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(OldRagno, OldRagnoEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(OldMagispeller, OldMagispellerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(MagiHeal, MagiHealEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Kaboomer, KaboomerEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(PumpkinBomb, PumpkinBombEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(OldAxe, OldAxeEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Scythe, ScytheEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(OldScythe, OldScytheEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(TrickOrTreat, TrickOrTreatEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(Web, WebEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(WebNet, WebNetEntity.createAttributes().build());
        FabricDefaultAttributeRegistry.register(VillagerSoul, VillagerSoulEntity.createAttributes().build());
    }

    static {
        Igniter = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "igniter"), Builder.of(IgniterEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build("illageandspillage:igniter"));
        Engineer = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "engineer"), Builder.of(EngineerEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build("illageandspillage:engineer"));
        ChagrinSentry = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "chagrin_sentry"), Builder.of(ChagrinSentryEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build("illageandspillage:chagrin_sentry"));
        Hinder = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "hinder"), Builder.of(HinderEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build("illageandspillage:hinder"));
        Factory = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "factory"), Builder.of(FactoryEntity::new, MobCategory.MONSTER).sized(1.2F, 0.95F).build("illageandspillage:factory"));
        Beeper = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "beeper"), Builder.of(BeeperEntity::new, MobCategory.MONSTER).sized(0.4F, 0.95F).build("illageandspillage:beeper"));
        Sniper = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "sniper"), Builder.of(SniperEntity::new, MobCategory.MONSTER).sized(0.5F, 0.95F).build("illageandspillage:sniper"));
        Poker = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "poker"), Builder.of(PokerEntity::new, MobCategory.MONSTER).sized(0.5F, 0.95F).build("illageandspillage:poker"));
        Magispeller = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "magispeller"), Builder.of(MagispellerEntity::new, MobCategory.MONSTER).sized(0.6F, 2.3F).build("illageandspillage:magispeller"));
        Faker = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "faker"), Builder.of(FakeMagispellerEntity::new, MobCategory.MONSTER).sized(0.6F, 2.3F).build("illageandspillage:faker"));
        Dispenser = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "dispenser"), Builder.of(DispenserEntity::new, MobCategory.MONSTER).sized(1.0F, 1.0F).build("illageandspillage:dispenser"));
        Illashooter = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "illashooter"), Builder.of(IllashooterEntity::new, MobCategory.MONSTER).sized(0.5F, 1.0F).build("illageandspillage:illashooter"));
        Crashager = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "crashager"), Builder.of(CrashagerEntity::new, MobCategory.MONSTER).sized(1.95F, 2.2F).fireImmune().build("illageandspillage:crashager"));
        BossRandomizer = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "boss_randomizer"), Builder.of(BossRandomizerEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build("illageandspillage:boss_randomizer"));
        Twittollager = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "twittollager"), Builder.of(TwittollagerEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build("illageandspillage:twittollager"));
        Spiritcaller = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "spiritcaller"), Builder.of(SpiritcallerEntity::new, MobCategory.MONSTER).sized(0.6F, 2.4F).build("illageandspillage:spiritcaller"));
        MobSpirit = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "mob_spirit"), Builder.of(MobSpiritEntity::new, MobCategory.MONSTER).sized(1.0F, 1.0F).fireImmune().build("illageandspillage:mob_spirit"));
        IllagerSoul = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "illager_soul"), Builder.of(IllagerSoulEntity::new, MobCategory.MONSTER).sized(1.0F, 1.0F).fireImmune().build("illageandspillage:illager_soul"));
        IgniterFireball = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "igniter_fireball"), Builder.<IgniterFireballEntity>of(IgniterFireballEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("illageandspillage:igniter_fireball"));
        Imp = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "imp"), Builder.of(ImpEntity::new, MobCategory.CREATURE).sized(1.0F, 3.0F).fireImmune().build("illageandspillage:imp"));
        SpiritHand = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "spirit_hand"), Builder.of(SpiritHandEntity::new, MobCategory.CREATURE).sized(1.5F, 1.5F).fireImmune().build("illageandspillage:spirit_hand"));
        SoulBeam = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "soul_beam"), Builder.<SoulBeamEntity>of(SoulBeamEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("illageandspillage:soul_beam"));
        Crocofang = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "crocofang"), Builder.of(CrocofangEntity::new, MobCategory.MONSTER).sized(2.0F, 1.4F).build("illageandspillage:crocofang"));
        CameraShake = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "camera_shake"), Builder.<CameraShakeEntity>of(CameraShakeEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("illageandspillage:camera_shake"));
//        Devastator = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "devastator"), Builder.of(DevastatorEntity::new, MobCategory.MONSTER).sized(5.4F, 8.75F).build("illageandspillage:devastator"));
        Absorber = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "absorber"), Builder.of(AbsorberEntity::new, MobCategory.MONSTER).sized(1.3F, 2.9F).build("illageandspillage:absorber"));
        Preserver = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "preserver"), Builder.of(PreserverEntity::new, MobCategory.MONSTER).sized(1.1F, 1.95F).build("illageandspillage:preserver"));
        Freakager = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "freakager"), Builder.of(FreakagerEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build("illageandspillage:freakager"));
        Ragno = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "ragno"), Builder.of(RagnoEntity::new, MobCategory.MONSTER).sized(3.2F, 1.8F).build("illageandspillage:ragno"));
        Eyesore = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "eyesore"), Builder.of(EyesoreEntity::new, MobCategory.MONSTER).sized(0.8F, 0.8F).build("illageandspillage:eyesore"));
        Funnybone = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "funnybone"), Builder.of(FunnyboneEntity::new, MobCategory.MONSTER).sized(0.5F, 1.2F).build("illageandspillage:funnybone"));
        Bone = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "bone"), Builder.<BoneEntity>of(BoneEntity::new, MobCategory.MONSTER).sized(0.5F, 0.1F).build("illageandspillage:bone"));
        SkullBomb = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "skull_bomb"), Builder.of(SkullBombEntity::new, MobCategory.MONSTER).sized(0.5F, 0.5F).build("illageandspillage:skull_bomb"));
        OldFreakager = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "old_freakager"), Builder.of(OldFreakagerEntity::new, MobCategory.MONSTER).sized(0.6F, 2.3F).build("illageandspillage:old_freakager"));
        OldRagno = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "old_ragno"), Builder.of(OldRagnoEntity::new, MobCategory.MONSTER).sized(3.2F, 1.8F).build("illageandspillage:old_ragno"));
        OldMagispeller = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "old_magispeller"), Builder.of(OldMagispellerEntity::new, MobCategory.MONSTER).sized(0.6F, 2.3F).build("illageandspillage:old_magispeller"));
        MagiFireball = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "magi_fireball"), Builder.<MagiFireballEntity>of(MagiFireballEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(1).build("illageandspillage:magi_fireball"));
        MagiArrow = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "magi_arrow"), Builder.<MagiArrowEntity>of(MagiArrowEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(1).build("illageandspillage:magi_arrow"));
        MagiHeal = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "magi_heal"), Builder.of(MagiHealEntity::new, MobCategory.MONSTER).sized(0.5F, 0.5F).build("illageandspillage:magi_heal"));
        Kaboomer = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "kaboomer"), Builder.of(KaboomerEntity::new, MobCategory.MONSTER).sized(1.25F, 3.4F).fireImmune().build("illageandspillage:kaboomer"));
        PumpkinBomb = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "pumpkin_bomb"), Builder.of(PumpkinBombEntity::new, MobCategory.MONSTER).sized(0.75F, 0.75F).build("illageandspillage:pumpkin_bomb"));
        Axe = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "axe"), Builder.<AxeEntity>of(AxeEntity::new, MobCategory.MONSTER).sized(0.2F, 0.2F).build("illageandspillage:axe"));
        OldAxe = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "old_axe"), Builder.of(OldAxeEntity::new, MobCategory.MONSTER).sized(0.2F, 0.2F).build("illageandspillage:old_axe"));
        DarkPotion = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "dark_potion"), Builder.of(DarkPotionEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(1).build("illageandspillage:dark_potion"));
        Scythe = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "scythe"), Builder.of(ScytheEntity::new, MobCategory.MONSTER).sized(0.2F, 0.2F).build("illageandspillage:scythe"));
        OldScythe = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "old_scythe"), Builder.of(OldScytheEntity::new, MobCategory.MONSTER).sized(0.2F, 0.2F).build("illageandspillage:old_scythe"));
        TrickOrTreat = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "trick_or_treat"), Builder.of(TrickOrTreatEntity::new, MobCategory.MONSTER).sized(1.0F, 1.8F).build("illageandspillage:trick_or_treat"));
        Web = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "web"), Builder.of(WebEntity::new, MobCategory.MONSTER).sized(0.2F, 0.2F).build("illageandspillage:web"));
        WebNet = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "web_net"), Builder.of(WebNetEntity::new, MobCategory.MONSTER).sized(0.2F, 0.2F).build("illageandspillage:web_net"));
        VillagerSoul = Registry.register(BuiltInRegistries.ENTITY_TYPE, new ResourceLocation(IllageAndSpillage.MOD_ID, "villager_soul"), Builder.of(VillagerSoulEntity::new, MobCategory.MONSTER).sized(1.0F, 1.0F).fireImmune().build("illageandspillage:villager_soul"));
    }

    public static void init() {

    }
}